---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.libvirt
  - name: infra.osbuild
  - name: redhat.insights
  - name: redhat.rhel_idm
  - name: redhat.rhel_system_roles
  - name: redhat.satellite
  - name: redhat.satellite_operations
