---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - name: Listen for a webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Push event to repository
      condition: 
        all:
          - event["payload"]["repository"]["name"] == "day2ops"
          - event["payload"]["head_commit"]["distinct"] == true
      action:
        run_job_template:
          name: "DAY2 - Deploy Web Content"
          organization: "Default"
          
